### ISSUE TITLE
[Bug] This implementation will introduce some color shift in some case.

### ISSUE THREAD

**Issue by 543877815** [hyperlogic/splatapult#16]
Hello, hyperlogic
I wanted to reach out to you regarding an issue I've encountered with your implementation. I appreciate the excellent work you've done, but I've come across something that seems like a bug.

I have trained the "coffee" dataset from Ref-NeRF, using the default training parameters provided on 3dgs. I proceeded to use the PLY model from the final step of 30,000 as the input for your implementation. Upon doing so, I noticed some unexpected color artifacts in the output. There appear to be small patches of green and purple color that weren't present here.
![image](https://github.com/hyperlogic/splatapult/assets/25082467/93fb778e-3650-477f-9f52-628f27d034c9)
In contrast, when I view the "ground truth" using SIBR viewers, the model appears clean and smooth, without any of the aforementioned color discrepancies.
![image](https://github.com/hyperlogic/splatapult/assets/25082467/6e23dbfe-0b96-4283-bcef-2530e5416b7a)

I would be grateful if you could provide some guidance or insight into this matter. Thank you for your attention to this issue, and I look forward to your response.

Best regards。

**Comment by hyperlogic** [comment]
Hmm, interesting, this looks like it could be due to accumulated error during alpha blending. By default, Splatapult uses a 32-bit color frame buffer (8 bits per component) during back to front rendering. It might be possible to change the code to pick a different bit-depth if the hardware supports it, for example fp16 per component, but higher bit depths would likely affect performance.

I'll take a look at the SIBR renderer to see what bit-depth it uses.

**Comment by hyperlogic** [comment]
I included an option to render into a half-float or float frame buffer, --fp16 and --fp32 respectively.  This eliminates the banding artifacts.

22ff61759ec4911296e4f1b0ba37db86c53e0e68
